export const C = {
  bg:      "var(--color-bg)",
  surface: "var(--color-surface)",
  card:    "var(--color-card)",
  border:  "var(--color-border)",
  borderD: "var(--color-border-d)",
  amber:   "var(--color-amber)",
  amberL:  "var(--color-amber-l)",
  amberBg: "var(--color-amber-bg)",
  amberA:  "var(--color-amber-a)",
  amberB:  "var(--color-amber-b)",
  amberC:  "var(--color-amber-c)",
  text:    "var(--color-text)",
  dim:     "var(--color-dim)",
  faint:   "var(--color-faint)",
  fainter: "var(--color-fainter)",
  green:   "var(--color-green)",
  greenBg: "var(--color-green-bg)",
  blue:    "var(--color-blue)",
  blueBg:  "var(--color-blue-bg)",
  blueA:   "var(--color-blue-a)",
  red:     "var(--color-red)",
  redA:    "var(--color-red-a)",
  navBg:   "var(--nav-bg)",
} as const;
